In [1]:
import numpy as np

### Define period bounds

In [218]:
period = 4200
np = 31

In [223]:
for i in range(np):
    print(i, period*i, period*(i+1));

0 0 4200
1 4200 8400
2 8400 12600
3 12600 16800
4 16800 21000
5 21000 25200
6 25200 29400
7 29400 33600
8 33600 37800
9 37800 42000
10 42000 46200
11 46200 50400
12 50400 54600
13 54600 58800
14 58800 63000
15 63000 67200
16 67200 71400
17 71400 75600
18 75600 79800
19 79800 84000
20 84000 88200
21 88200 92400
22 92400 96600
23 96600 100800
24 100800 105000
25 105000 109200
26 109200 113400
27 113400 117600
28 117600 121800
29 121800 126000
30 126000 130200


In [ ]:
for i in range(np):
    print(i, period*i, period*(i+1));

### Solenoid positions

In [ ]:
sol_z = np.array([500, 1200, 1900, 2600, 3300, 4000])

### RF cavity positions

In [70]:
vals = []
for i in range(0, 32):
    for j in range(6):
        for c in [-125, +125]:
            vals.append(i*4200 + 500 + j*700 + c)

vals = np.array(vals)

In [182]:
#### Get z vals for a set of RFs given the period number:

def rfz(i):
    vals = []
    for j in range(6):
            for c in [-125, +125]:
                vals.append(i*4200 + 500 + j*700 + c)
    return np.array(vals)

initvals = rfz(0)

In [215]:
initvals 

array([ 375,  625, 1075, 1325, 1775, 2025, 2475, 2725, 3175, 3425, 3875,
       4125])

In [214]:
print("define HFOFORFCPeriodB \\")
for i, z in enumerate(initvals[6:]):
    print('    "place $1 ' + "z=" + f'{z}' + '+$period*$2 timeOffset' + f"=${i+3}" + '" \\')

define HFOFORFCPeriodB \
    "place $1 z=2475+$period*$2 timeOffset=$3" \
    "place $1 z=2725+$period*$2 timeOffset=$4" \
    "place $1 z=3175+$period*$2 timeOffset=$5" \
    "place $1 z=3425+$period*$2 timeOffset=$6" \
    "place $1 z=3875+$period*$2 timeOffset=$7" \
    "place $1 z=4125+$period*$2 timeOffset=$8" \


In [212]:
initvals / 5000

array([0.075, 0.125, 0.215, 0.265, 0.355, 0.405, 0.495, 0.545, 0.635,
       0.685, 0.775, 0.825])

In [217]:
for i in range(31):
    print(initvals[0] + 4200*i)

375
4575
8775
12975
17175
21375
25575
29775
33975
38175
42375
46575
50775
54975
59175
63375
67575
71775
75975
80175
84375
88575
92775
96975
101175
105375
109575
113775
117975
122175
126375


In [80]:
v1, v2 = vals[0:12], vals[12:24]

In [174]:
def fn(v, scalingfactor=0.00321):
    offset = ((v%700)-500)
    off = (offset + 125) / 250
    return ((((v % 4200) - offset)-500))/350 + off

print(fn(v1))
print(fn(v2))

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]


In [131]:
def fn(v, scalingfactor=0.00321):
    return np.ceil(((v % 4200) + 125 - 500) * scalingfactor).astype(int)

print(fn(v1))
print(fn(v2))

[ 0  1  3  4  5  6  7  8  9 10 12 13]
[ 0  1  3  4  5  6  7  8  9 10 12 13]


[   0  250  700  950 1400 1650 2100 2350 2800 3050 3500 3750]
[   0  250  700  950 1400 1650 2100 2350 2800 3050 3500 3750]


### Absorber tube positions

In [22]:
ini = [150, 850, 1550, 2250, 2950, 3650]
period = 4200
### Absorber values 
valsraw = []
for i in range(1, 31):
    for iniz in ini:
        valsraw.append(iniz + i*period)

valsraw = np.array(valsraw)

In [36]:
inizz = 150
nsol = 6
period = 4200
mult = int(period / nsol)
### Absorber values 
vals = []
for i in range(1, 31):
    for j in range(6):
        inn = inizz + j*mult + i*period
        vals.append(inn)

vals = np.array(vals)

In [40]:
init_abs_z = np.array([850, 1550, 2250, 2950, 3650])
all_abs_z = np.concatenate([init_abs_z, vals])

### Terminus positions

In [43]:
terminus_z = [-1000, 4200*31+1450+102]

In [44]:
terminus_z

[-1000, 131752]